### ISSUE TITLE
Safari support information

### ISSUE THREAD

**Issue by TomasHubelbauer** [wide-video/app-ffmpeg#1]
Hi, as per https://github.com/wide-video/app-ffmpeg/blob/main/TODO.md there is testing needed for Safari. I gave it a quick spin.

First I tried this in Firefox to get a baseline of excepted behavior: I dragged in a JPG file and used `ffmpeg -i autumn-5k-peter-k-burian.jpg -preset ultrafast output.png` to convert to PNG. The `output.png` file was created in the virtual FS as well as its preview was displayed after the command ran. The WASM related bits got pulled in and executed successfully.

I didn't test a video or audio conversion, but I assume since the image conversion works, everything will.

The only problem is the lack of blinking cursor in the terminal on Firefox.

Next I tried to do the same on Safari and I was able to drag in the file as well. I then tried to use `ls` to check it was on the virtual FS, but I couldn't type into the terminal at all on Safari. I couldn't try any other steps as a result. There are no errors in the console. I am on macOS Sonoma 14.5.

Let me know if you need any other help with Safari/Firefox testing on macOS.

**Comment by jozefchutka** [comment]
Hi Tomas,

thanks for reporting. I will have a look on the firefox issue with cursor today and will have access to mac/safari tomorrow - will fix the necessary.

**Comment by jozefchutka** [comment]
firefox caret fixed in https://github.com/wide-video/app-ffmpeg/commit/7a78a8f803367a48d70edb6842b7715a5893a40e

**Comment by jozefchutka** [comment]
fixed safari cared in https://github.com/wide-video/app-ffmpeg/commit/fa918446a959fce8b31d60578466364771d8bfe2

**Comment by TomasHubelbauer** [comment]
Can confirm both work for me now!
